/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BorrowOps } from "./BorrowOps";
export * as factories from "./factories";
export { BorrowOps__factory } from "./factories/BorrowOps__factory";
