query ($orderBy: String!, $orderDirection: String!) {
  liquidations(first: 10, orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    vault {
      id
    }
    timestamp
    debt
    collateral
    liquidator
  }
}
