query ($orderBy: String!, $orderDirection: String!) {
  redemptions(first: 10, orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    vault {
      id
    }
    timestamp
    collateralSent
    redeemer
    undReceived
  }
}
